### ISSUE TITLE
.obj -> .gombz

### ISSUE THREAD

**Issue by sg3des** [tbogdala/gombz#1]
I can not understand, how transform/convert .obj(or other) 3d model to .gombz format?
may be some example?

**Comment by tbogdala** [comment]
I'll try and update the README file soon, but basically this library does not do the conversion. It simply handles the loading and saving of a custom binary model format. At present, the binary serialization is done with BSON (implementation: http://gopkg.in/mgo.v2/bson). The rest is just the declaration of the structures. How the structures get filled in is the job of another library.

That other library is http://github.com/tbogdala/assimp-go. You can clone that repo, cd to the `compiler` directory, build & run as per the README of that project. This will create a model compiler that should take anything that ASSIMP can take (fbx, obj, etc...) and output a gombz binary.

These were kept separate so that client applications can import gombz without having the ASSIMP dependency.

**Comment by sg3des** [comment]
thx, convert and import was successful! 
_I used assimp 3.2-2 (last from Arch repository)_

**Comment by tbogdala** [comment]
Excellent! Thanks for all the issue submissions across my repositories, by the way. I appreciate the feedback. I'm working on a game that I hope to open source within a month or so to help illustrate how to tie things together.
